### ISSUE TITLE
CLI arg to filter files appear in the coverage data

### ISSUE THREAD

**Issue by jayvdb** [amalfra/lcov-cli-report-viewer#7]
As the output can be quite large, it would be useful to be able to filter to show only a single file, or files under a directory.

**Comment by amalfra** [comment]
@jayvdb Thanks for the suggestion. This would be a really useful feature. I will plan to have this included in the next major release(v 2.0).

**Comment by amalfra** [comment]
@jayvdb This is added in [v2.0](https://github.com/amalfra/lcov-cli-report-viewer/releases/tag/2.0.0) that's released now!!!
